In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel
#print(M)

In [2]:
df=pd.read_csv('x_train.csv')
#df['SalePrice']=np.log(df['SalePrice'])
#df.drop('Unnamed: 0',axis=1,inplace=True)

In [3]:
df

Id  SalePrice  MSSubClass  MSZoning  LotFrontage   LotArea  Street  \
0        1     208500    0.235294       0.5     0.418208  0.366344     0.0   
1        2     181500    0.000000       0.5     0.495064  0.391317     0.0   
2        3     223500    0.235294       0.5     0.434909  0.422359     0.0   
3        4     140000    0.294118       0.5     0.388581  0.390295     0.0   
4        5     250000    0.235294       0.5     0.513123  0.468761     0.0   
...    ...        ...         ...       ...          ...       ...     ...   
1455  1456     175000    0.235294       0.5     0.400718  0.353592     0.0   
1456  1457     210000    0.000000       0.5     0.517503  0.453273     0.0   
1457  1458     266500    0.294118       0.5     0.423859  0.379597     0.0   
1458  1459     142125    0.000000       0.5     0.434909  0.393688     0.0   
1459  1460     147500    0.000000       0.5     0.471175  0.398069     0.0   

      Alley  LotShape  LandContour  ...  Fence  MiscFeature  MiscVal  \
0       1.0       1.0          1.0  ...    1.0          1.0  0.00000   
1       1.0       1.0          1.0  ...    1.0          1.0  0.00000   
2       1.0       0.0          1.0  ...    1.0          1.0  0.00000   
3       1.0       0.0          1.0  ...    1.0          1.0  0.00000   
4       1.0       0.0          1.0  ...    1.0          1.0  0.00000   
...     ...       ...          ...  ...    ...          ...      ...   
1455    1.0       1.0          1.0  ...    1.0          1.0  0.00000   
1456    1.0       1.0          1.0  ...    0.5          1.0  0.00000   
1457    1.0       1.0          1.0  ...    0.0          0.5  0.16129   
1458    1.0       1.0          1.0  ...    1.0          1.0  0.00000   
1459    1.0       1.0          1.0  ...    1.0          1.0  0.00000   

        MoSold  YrSold  SaleType  SaleCondition  LotFrontagenan  \
0     0.090909    0.50       1.0            0.5             0.0   
1     0.363636    0.25       1.0            0.5             0.0   
2     0.727273    0.50       1.0            0.5             0.0   
3     0.090909    0.00       1.0            0.0             0.0   
4     1.000000    0.50       1.0            0.5             0.0   
...        ...     ...       ...            ...             ...   
1455  0.636364    0.25       1.0            0.5             0.0   
1456  0.090909    1.00       1.0            0.5             0.0   
1457  0.363636    1.00       1.0            0.5             0.0   
1458  0.272727    1.00       1.0            0.5             0.0   
1459  0.454545    0.50       1.0            0.5             0.0   

      MasVnrAreanan  GarageYrBltnan  
0               0.0             0.0  
1               0.0             0.0  
2               0.0             0.0  
3               0.0             0.0  
4               0.0             0.0  
...             ...             ...  
1455            0.0             0.0  
1456            0.0             0.0  
1457            0.0             0.0  
1458            0.0             0.0  
1459            0.0             0.0  

[1460 rows x 84 columns]

In [5]:
x_train=df.drop(['Id','SalePrice'],axis=1)
d={}
for i in x_train.columns:
    d[i]=x_train[i].isnull().sum()
    #(x_train[i].isnull().sum(),i)
d    
zx=[]
for d,v in d.items():
    if v>1:
        zx.append(d)
zx
for f in zx:
    median_val=x_train[f].median()
    x_train[f].fillna(median_val,inplace=True)

In [6]:

d={}
for i in x_train.columns:
    d[i]=x_train[i].isnull().sum()
d

{'MSSubClass': 0,
 'MSZoning': 0,
 'LotFrontage': 0,
 'LotArea': 0,
 'Street': 0,
 'Alley': 0,
 'LotShape': 0,
 'LandContour': 0,
 'Utilities': 0,
 'LotConfig': 0,
 'LandSlope': 0,
 'Neighborhood': 0,
 'Condition1': 0,
 'Condition2': 0,
 'BldgType': 0,
 'HouseStyle': 0,
 'OverallQual': 0,
 'OverallCond': 0,
 'YearBuilt': 0,
 'YearRemodAdd': 0,
 'RoofStyle': 0,
 'RoofMatl': 0,
 'Exterior1st': 0,
 'Exterior2nd': 0,
 'MasVnrType': 0,
 'MasVnrArea': 0,
 'ExterQual': 0,
 'ExterCond': 0,
 'Foundation': 0,
 'BsmtQual': 0,
 'BsmtCond': 0,
 'BsmtExposure': 0,
 'BsmtFinType1': 0,
 'BsmtFinSF1': 0,
 'BsmtFinType2': 0,
 'BsmtFinSF2': 0,
 'BsmtUnfSF': 0,
 'TotalBsmtSF': 0,
 'Heating': 0,
 'HeatingQC': 0,
 'CentralAir': 0,
 'Electrical': 0,
 '1stFlrSF': 0,
 '2ndFlrSF': 0,
 'LowQualFinSF': 0,
 'GrLivArea': 0,
 'BsmtFullBath': 0,
 'BsmtHalfBath': 0,
 'FullBath': 0,
 'HalfBath': 0,
 'BedroomAbvGr': 0,
 'KitchenAbvGr': 0,
 'KitchenQual': 0,
 'TotRmsAbvGrd': 0,
 'Functional': 0,
 'Fireplaces': 0,
 'Firep

In [7]:
y_train=df.SalePrice


In [8]:
feat_select_model=SelectFromModel(Lasso(alpha=0.005,normalize=True, max_iter=1e5,random_state=0))
feat_select_model.fit(x_train,y_train) ## lasso 

SelectFromModel(estimator=Lasso(alpha=0.005, max_iter=100000.0, normalize=True,
                                random_state=0))

In [9]:
feat_select_model.get_support()## getting important features(columns) in the dataset 

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [10]:
selected_columns=x_train.columns[(feat_select_model.get_support())]
selected_columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'Wo

In [11]:
print('total features :{}'.format(x_train.shape[1]))
print('selected featues :{}'.format(len(selected_columns)))
print('features whose co efficient is zero: {}'.format(np.sum(feat_select_model.estimator_.coef_==0)))

total features :82
selected featues :82
features whose co efficient is zero: 0


In [12]:
xx_train=x_train[selected_columns]
xx_train.head()

MSSubClass  MSZoning  LotFrontage   LotArea  Street  Alley  LotShape  \
0    0.235294       0.5     0.418208  0.366344     0.0    1.0       1.0   
1    0.000000       0.5     0.495064  0.391317     0.0    1.0       1.0   
2    0.235294       0.5     0.434909  0.422359     0.0    1.0       0.0   
3    0.294118       0.5     0.388581  0.390295     0.0    1.0       0.0   
4    0.235294       0.5     0.513123  0.468761     0.0    1.0       0.0   

   LandContour  Utilities  LotConfig  ...  Fence  MiscFeature  MiscVal  \
0          1.0        0.0       0.75  ...    1.0          1.0      0.0   
1          1.0        0.0       0.50  ...    1.0          1.0      0.0   
2          1.0        0.0       0.75  ...    1.0          1.0      0.0   
3          1.0        0.0       0.00  ...    1.0          1.0      0.0   
4          1.0        0.0       0.50  ...    1.0          1.0      0.0   

     MoSold  YrSold  SaleType  SaleCondition  LotFrontagenan  MasVnrAreanan  \
0  0.090909    0.50       1.0            0.5             0.0            0.0   
1  0.363636    0.25       1.0            0.5             0.0            0.0   
2  0.727273    0.50       1.0            0.5             0.0            0.0   
3  0.090909    0.00       1.0            0.0             0.0            0.0   
4  1.000000    0.50       1.0            0.5             0.0            0.0   

   GarageYrBltnan  
0             0.0  
1             0.0  
2             0.0  
3             0.0  
4             0.0  

[5 rows x 82 columns]

In [13]:
x_test=pd.read_csv('scaled_test_data.csv')
x_test


Id  MSSubClass  MSZoning  LotFrontage   LotArea  Street  Alley  \
0     1461    0.000000       0.4     0.329609  0.184147     1.0    1.0   
1     1462    0.000000       0.6     0.335196  0.232124     1.0    1.0   
2     1463    0.235294       0.6     0.296089  0.224197     1.0    1.0   
3     1464    0.235294       0.6     0.318436  0.154326     1.0    1.0   
4     1465    0.588235       0.6     0.122905  0.064121     1.0    1.0   
...    ...         ...       ...          ...       ...     ...    ...   
1454  2915    0.823529       0.8     0.000000  0.008453     1.0    1.0   
1455  2916    0.823529       0.8     0.000000  0.007691     1.0    1.0   
1456  2917    0.000000       0.6     0.776536  0.336115     1.0    1.0   
1457  2918    0.382353       0.6     0.229050  0.162724     1.0    1.0   
1458  2919    0.235294       0.6     0.296089  0.147959     1.0    1.0   

      LotShape  LandContour  Utilities  ...  Fence  MiscFeature   MiscVal  \
0          1.0     1.000000        0.0  ...    0.5     1.000000  0.000000   
1          0.0     1.000000        0.0  ...    1.0     0.000000  0.735294   
2          0.0     1.000000        0.0  ...    0.5     1.000000  0.000000   
3          0.0     1.000000        0.0  ...    1.0     1.000000  0.000000   
4          0.0     0.333333        0.0  ...    1.0     1.000000  0.000000   
...        ...          ...        ...  ...    ...          ...       ...   
1454       1.0     1.000000        0.0  ...    1.0     1.000000  0.000000   
1455       1.0     1.000000        0.0  ...    1.0     1.000000  0.000000   
1456       1.0     1.000000        0.0  ...    1.0     1.000000  0.000000   
1457       1.0     1.000000        0.0  ...    0.5     0.666667  0.041176   
1458       1.0     1.000000        0.0  ...    1.0     1.000000  0.000000   

        MoSold  YrSold  SaleType  SaleCondition  LotFrontagenan  \
0     0.454545     1.0  0.888889            0.8             0.0   
1     0.454545     1.0  0.888889            0.8             0.0   
2     0.181818     1.0  0.888889            0.8             0.0   
3     0.454545     1.0  0.888889            0.8             0.0   
4     0.000000     1.0  0.888889            0.8             0.0   
...        ...     ...       ...            ...             ...   
1454  0.454545     0.0  0.888889            0.8             0.0   
1455  0.272727     0.0  0.888889            0.0             0.0   
1456  0.727273     0.0  0.888889            0.0             0.0   
1457  0.545455     0.0  0.888889            0.8             0.0   
1458  0.909091     0.0  0.888889            0.8             0.0   

      MasVnrAreanan  GarageYrBltnan  
0               0.0             0.0  
1               0.0             0.0  
2               0.0             0.0  
3               0.0             0.0  
4               0.0             0.0  
...             ...             ...  
1454            0.0             1.0  
1455            0.0             0.0  
1456            0.0             0.0  
1457            0.0             1.0  
1458            0.0             0.0  

[1459 rows x 83 columns]

In [14]:
xx_test=x_test[selected_columns]
#xx_test
d={}
for i in xx_test.columns:
    d[i]=xx_test[i].isnull().sum()
    #(x_train[i].isnull().sum(),i)
d    
zx=[]
for d,v in d.items():
    if v>=1:
        zx.append(d)
zx
for f in zx:
    median_val=xx_test[f].median()
    xx_test[f].fillna(median_val,inplace=True)

C:\Users\blank.space\anaconda3\lib\site-packages\pandas\core\series.py:4463: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(


In [258]:
y_train

0       208500
1       181500
2       223500
3       140000
4       250000
         ...  
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [16]:


from sklearn.linear_model           import LinearRegression

from sklearn.tree                   import DecisionTreeRegressor

from sklearn import tree

In [17]:
m1=LinearRegression()
m2=DecisionTreeRegressor(max_depth=9)



In [18]:
from sklearn.model_selection import cross_val_score


In [19]:
from sklearn.model_selection import train_test_split
x_t,x_tes,y_t,y_tes = train_test_split(xx_train,y_train,random_state=0,test_size=0.2)

In [20]:
scores= cross_val_score(m2,xx_train,y_train,cv=5)
scores

array([0.74127914, 0.6808301 , 0.80144628, 0.74087329, 0.60431199])

In [21]:
m2.fit(xx_train,y_train)
m2.score(xx_train,y_train)



0.9722010445258201

In [353]:
predicted_data=m2.predict(xx_test)
predicted_data

array([100000., 100000., 145900., ..., 100000., 109095., 139700.])

In [354]:
testt=pd.DataFrame(predicted_data,index=x_test['Id'])
testt.columns=['SalePrice']
#testt.to_csv('depth_03.csv')

In [355]:
testt

SalePrice
Id             
1461   100000.0
1462   100000.0
1463   145900.0
1464   145900.0
1465   230000.0
...         ...
2915   127500.0
2916   109707.5
2917   100000.0
2918   109095.0
2919   139700.0

[1459 rows x 1 columns]